server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cultivationSimulator?characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
jwt:
  secret: ABCDE # JWT签名密钥
  expiration: 86400000         # JWT过期时间（毫秒）